[2024-10-26T20:35:12.276+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-26T20:35:12.295+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_branch_operator.ext_py_a scheduled__2024-10-25T00:00:00+00:00 [queued]>
[2024-10-26T20:35:12.304+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_branch_operator.ext_py_a scheduled__2024-10-25T00:00:00+00:00 [queued]>
[2024-10-26T20:35:12.306+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-26T20:35:12.319+0000] {taskinstance.py:2888} INFO - Executing <Task(ExternalPythonOperator): ext_py_a> on 2024-10-25 00:00:00+00:00
[2024-10-26T20:35:12.328+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=163) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-26T20:35:12.329+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'example_branch_operator', 'ext_py_a', 'scheduled__2024-10-25T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', '/home/***/.local/lib/python3.12/site-packages/***/example_dags/example_branch_operator.py', '--cfg-path', '/tmp/tmpwfukl482']
[2024-10-26T20:35:12.330+0000] {standard_task_runner.py:72} INFO - Started process 165 to run task
[2024-10-26T20:35:12.330+0000] {standard_task_runner.py:105} INFO - Job 7: Subtask ext_py_a
[2024-10-26T20:35:12.375+0000] {task_command.py:467} INFO - Running <TaskInstance: example_branch_operator.ext_py_a scheduled__2024-10-25T00:00:00+00:00 [running]> on host c94222e110db
[2024-10-26T20:35:12.442+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_branch_operator' AIRFLOW_CTX_TASK_ID='ext_py_a' AIRFLOW_CTX_EXECUTION_DATE='2024-10-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-25T00:00:00+00:00'
[2024-10-26T20:35:12.445+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-26T20:35:12.445+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-26T20:35:12.446+0000] {logging_mixin.py:190} INFO - Current task name:ext_py_a state:running start_date:2024-10-26 20:35:12.296456+00:00
[2024-10-26T20:35:12.447+0000] {logging_mixin.py:190} INFO - Dag name:example_branch_operator and current dag run status:running
[2024-10-26T20:35:12.448+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-26T20:35:12.795+0000] {baseoperator.py:405} WARNING - ExternalPythonOperator.execute cannot be called outside TaskInstance!
[2024-10-26T20:35:12.834+0000] {process_utils.py:186} INFO - Executing cmd: /home/***/.local/bin/python /tmp/venv-callavijqn23/script.py /tmp/venv-callavijqn23/script.in /tmp/venv-callavijqn23/script.out /tmp/venv-callavijqn23/string_args.txt /tmp/venv-callavijqn23/termination.log
[2024-10-26T20:35:12.835+0000] {process_utils.py:190} INFO - Output:
[2024-10-26T20:35:16.253+0000] {process_utils.py:194} INFO - Hello World from external Python
[2024-10-26T20:35:16.709+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-26T20:35:16.720+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-26T20:35:16.721+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=example_branch_operator, task_id=ext_py_a, run_id=scheduled__2024-10-25T00:00:00+00:00, execution_date=20241025T000000, start_date=20241026T203512, end_date=20241026T203516
[2024-10-26T20:35:16.733+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-10-26T20:35:16.734+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-10-26T20:35:16.735+0000] {logging_mixin.py:190} INFO - Dag name:example_branch_operator queued_at:2024-10-26 20:34:59.272543+00:00
[2024-10-26T20:35:16.735+0000] {logging_mixin.py:190} INFO - Task hostname:c94222e110db operator:ExternalPythonOperator
[2024-10-26T20:35:16.767+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-26T20:35:16.804+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-26T20:35:16.807+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
